baseurl                 = "https:/www.shootbird.work/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "ShootBird"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"

publishDir = "docs"
enableRobotsTXT = true
canonifyURLs = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.png"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "©2018 [zed](https://www.zeddee.com/)."
  profileImage      = "/zed-square-400px.jpg"
  postFooterText      = """
  **Author |** Zed is a former educator and currently a
  [professional explainer](https://www.zeddee.com/cv).
  He writes about software, video games, and narrative design.
  If you have software or a system that needs explaining
  (to frustrated users, or you just need someone to write
  stuff down for you), you can contact him for work at
  [zed@nsdmdh.com](mailto://zed@nsdmdh.com).
  """
  mainSiteDescription = """
  **ShootBird** is a small technical writing consultancy. We provide writing services for companies who want to build customer trust with well-researched and highly-readable content.
  """
  cta = "Ping [zed@nsdmdh.com](mailto://zed@nsdmdh.com) for questions and quotes."

# Metadata
    # description         = "Shoot Bird provides writing services for organisations who need well-researched technical content to build user trust and reduce customer support load."            # Max 160 characters show in search results
    description         = "We write tech things for you."
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/img/logo/shootbird_opengraph.png"                     # Image that shows on Twitter cards and OpenGraph links
    headerImage         = "/img/logo/shootbird_logo_beak.png"

[[params.mainMenu]]
    link = "/what-is-shootbird"
    text = "打鳥 (shoot bird?)"

[[params.mainMenu]]
    link = "/hire-us"
    text = "hire us"

[[params.mainMenu]]
    link = "/posts"
    text = "blog"

# [[params.mainMenu]]
#     link = "/gallery"
#     text = "gallery"
