baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "Shoot Bird"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"

publishDir = "docs"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.png"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    smallPreviewImages   = true                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "©2018 [zed](https://www.zeddee.com/)."
  profileImage      = "/zed-square-400px.jpg"
  postFooterText      = """
  Zed is a former educator and currently a
  [professional explainer](https://www.zeddee.com/cv).
  He writes about software, video games, and narrative design.
  If you have software or a system that needs explaining
  (to frustrated users, or you just need someone to write
  stuff down for you), you can contact him for work at
  [zed@nsdmdh.com](mailto://zed@nsdmdh.com).
  """

# Metadata
    description         = "Off centre."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/img/logo/shootbird_logo_beak.png"                     # Image that shows on Twitter cards and OpenGraph links
  headerImage         = "/img/logo/shootbird_logo_beak.png"




[[params.mainMenu]]
    link = "/services"
    text = "services"

[[params.mainMenu]]
    link = "/what-is-shoot-bird"
    text = "打鳥 (shoot bird?)"

[[params.mainMenu]]
    link = "/posts"
    text = "blog"
# [[params.mainMenu]]
#     link = "/gallery"
#     text = "gallery"
